# Generated by Django 5.0.4 on 2024-06-29 05:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('standard_name', models.CharField(max_length=100, unique=True)),
                ('image', models.FileField(upload_to='image/standard')),
            ],
            options={
                'db_table': 'standard',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('subject_name', models.CharField(max_length=50)),
                ('subject_image', models.FileField(upload_to='image/subject')),
                ('standard_id', models.ForeignKey(db_column='standard_id', on_delete=django.db.models.deletion.CASCADE, related_name='standard_subjects', to='courses.standard')),
            ],
            options={
                'db_table': 'subject',
            },
        ),
    ]
